services:
  - type: web
    name: querylite
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
      - key: MAX_TOKENS
        value: "2048"
      - key: TEMPERATURE
        value: "0.1"
